version: "3"

services:
  tomcat:
    build:
      context: ./TomcatServer
      dockerfile: Dockerfile
    container_name: tomcat
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./TomcatServer:/workspace

  erlang:
    image: erlang:latest
    build:
      context: ./ErlangServer
      dockerfile: Dockerfile
    container_name: erlang
    ports:
      - 8081:8080
    stdin_open: true
    tty: true
    volumes:
      - ./ErlangServer:/workspace

  mysql:
    image: mysql:latest
    container_name: database
    ports:
      - 8082:3306
    stdin_open: true
    tty: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=""
    volumes:
      - ./Database/data:/var/lib/mysql
