version: "3"

services:
  tomcat:
    build:
      context: ./TomcatServer
      dockerfile: Dockerfile
    container_name: tomcat
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=mysql
      - DB_ROOT=root
      - DB_PASS=root
      - DB_PORT=3306
      - DB_NAME=app
    ports:
      - 8080:8080
    volumes:
      - ./TomcatServer:/workspace

  erlang:
    build:
      context: ./ErlangServer
      dockerfile: Dockerfile
    container_name: erlang
    ports:
      - 8081:8080
    stdin_open: true
    tty: true
    volumes:
      - ./ErlangServer:/workspace

  mysql:
    image: mysql:latest
    container_name: database
    ports:
      - 8082:3306
    stdin_open: true
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./Database/data:/var/lib/mysql
