version: "3"

services:
  tomcat:
    build:
      context: ./TomcatServer
    container_name: tomcat
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./TomcatServer:/workspace

  erlang:
    image: erlang:latest
    container_name: erlang
    stdin_open: true
    tty: true
    volumes:
      - ./ErlangServer:/workspace

  mysql:
    image: mysql:latest
    container_name: database
    stdin_open: true
    tty: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=""
    volumes:
      - ./Database:/workspace

  client:
    image: node:latest
    container_name: frontend
    stdin_open: true
    tty: true
    volumes:
      - ./Client:/workspace
